language: rust
cache: cargo
rust:
  - 1.15.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose -- --test-threads=1 --nocapture
matrix:
  allow_failures:
    - rust: nightly
